### ISSUE TITLE
tikzducks v0.5 is incompatible with LuaLaTeX and XeLaTeX

### ISSUE THREAD

**Issue by yudai-nkt** [samcarter8/tikzducks#14]
After updating TeX Live on my end, I got interested in how `\randuck` is implemented and found the following line. https://github.com/samcarter8/tikzducks/blob/2f69d05fef84253fb6ff60081c2eb5d78b72b653/tikzducks.sty#L767

LuaTeX of version 0.81.0 or higher and XeTeX don't have the primitive `\pdfrandomseed` whereas pdfTeX and e-(u)pTeX do. Therefore, the following MWE

```latex
\documentclass{article}
\usepackage{tikzducks}
\begin{document}
\end{document}
```

cannot be typeset with XeLaTeX and LuaLaTeX.

Solution with LuaLaTeX is easy; you only need to `\let` `\pdfrandomseed` to be `\randomseed` (possibly with version checking). There seems to have been [a discussion](https://tug.org/pipermail/xetex/2016-November/thread.html#26840) about PRNG in XeTeX, but I don't have time to read all the thread at the moment and XeTeX doesn't have a primitive named `\randomseed`.

```
~$ xetex -interaction=nonstopmode "\show\randomseed\bye"
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xetex)
 restricted \write18 enabled.
entering extended mode
> \randomseed=undefined.
<*> \show\randomseed
                    \bye
(see the transcript file for additional information)
No pages of output.
Transcript written on texput.log.
```

**Comment by ghost** [comment]
@yudai-nkt Thanks a lot for reporting this bug!

I tried to implement a workaround which 
- uses the `\randomseed` you suggested for lualatex
- uses a fixed seed for xelatex (and added a warning about this to the documentation).

**Comment by ghost** [comment]
Now using `\pgfmathsetseed{\time}` for xelatex
Updates only once per minute, but generally works

**Comment by yudai-nkt** [comment]
Thank you for the quick fix! In addition to 7d836bb, something like

```latex
\RequirePackage{ifluatex}
\RequirePackage{ifxetex}

\ifluatex
  \let\pdfrandomseed\randomseed
\fi

\ifxetex
  \pgfmathsetseed{\time}
\else
  \pgfmathsetseed{\number\pdfrandomseed}
\fi
```

will utilize e-(u)pTeX's `\pdfrandomseed`, which can be a better seed (you aren't making an encryption, but it's better indeed), for (u)pLaTeX, which are Japanese variants of LaTeX. I'll be glad if you support the use of `\pdfrandomseed` in (u)pLaTeX as well although the number of users are considerably smaller than that of other engines.

My follow-up isn't a bug report but just a proposal of enhancement, so I never mean to rush you. Thanks again.

**Comment by ghost** [comment]
@yudai-nkt Thanks a lot for your comment! I'll happily integrate your code suggestion into the package, no matter how big or small the number of users might be. If such a small change helps someone it is worth doing it (especially as I cannot see any real drawbacks of the new code). It works just fine from what I can tell!

I had already submitted the bug fix https://github.com/samcarter8/tikzducks/commit/7d836bb4384bd8df2ad216441f652e9d0d5de0c0 to CTAN in order to make the package usable again as soon as possible, so I will include  https://github.com/samcarter8/tikzducks/commit/ef333d1e3d753c1cfab0424cc3b0dfc8d43d86af only in the next version of the package.

Please report again, if you happen to notice any other problems between the tikzducks package and (u)pLaTeX (I have to admit, these are engines I don't use regularly -- in fact today was probably the first time I did :)

**Comment by yudai-nkt** [comment]
> no matter how big or small the number of users might be. If such a small change helps someone it is worth doing it

Much appreciated for the kind words. Also looking forward to the next release! :sparkles::duck:

**Comment by samcarter** [comment]
@yudai-nkt Please excuse me for pinging you about this old thread, but I just made some changes about the random seed because as of 2019 xelatex now also supports the `\randomseed` primitive. 

https://github.com/samcarter/tikzducks/commit/da3228e232279a2a342d062b8d524dbaa5a1f24a

Would you be able to test with (u)pLaTeX? I would be very grateful to hear your feedback!  Thanks in advance!
