### ISSUE TITLE
Scale scales y and x shift

### ISSUE THREAD

**Issue by JoniBue1** [samcarter8/tikzducks#36]
Hello there,
I don't know if it is wanted like this but the scale option scales also the x and y shift. I've got a MWE :
```
\documentclass{minimal}
\usepackage{tikzducks}
\usepackage{tikz}
\begin{document}
	\begin{tikzpicture}
		\duck[scale=0.4, xshift=30pt]
		\duck[scale=2, xshift=30pt]
	\end{tikzpicture}
\end{document}
```
When you comile this you can see, that the big duck is shifted from the little one, as it should be at the same shift.
![grafik](https://github.com/samcarter/tikzducks/assets/132902444/169a2c0b-3d6d-4714-97b4-9e71a5954f12)

**Comment by samcarter** [comment]
Thanks for the report!

This is the typical TikZ behaviour:

```
\documentclass{standalone}
\usepackage{tikz}
\begin{document}
	\begin{tikzpicture}
		\draw[scale=0.4, xshift=30pt] circle [radius=3mm];
		\draw[scale=2, xshift=30pt] circle [radius=3mm];
	\end{tikzpicture}
\end{document}
```

![document-1](https://github.com/samcarter/tikzducks/assets/43832342/36bd4bfa-635e-4316-bf28-391c739d76f0)

... so I consider this status by design.

If you want to shift them by the same amount, you could use
```
\documentclass{standalone}
\usepackage{tikzducks}
\usepackage{tikz}
\begin{document}
	\begin{tikzpicture}
		\duck[xshift=30pt,scale=0.4]
		\duck[xshift=30pt,scale=2]
	\end{tikzpicture}
\end{document}
```

![document-1](https://github.com/samcarter/tikzducks/assets/43832342/a829afbf-de6e-48bc-874a-2623b717facd)

**Comment by muzimuzhi** [comment]
Coordinate transformations in TikZ are applied incrementally, thus the order matters.

> Rather, all you can do is to “add” another transformation to the current matrix.
https://tikz.dev/tikz-transformations#sec-25.3
